# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_pb2 as robot__pb2


class RobotControllerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Move = channel.unary_unary(
                '/AiInvest.Robotics.GrpcServer.RobotControllerServer/Move',
                request_serializer=robot__pb2.MotorAnglesRequest.SerializeToString,
                response_deserializer=robot__pb2.MotorAnglesResponse.FromString,
                )
        self.GetAngles = channel.unary_unary(
                '/AiInvest.Robotics.GrpcServer.RobotControllerServer/GetAngles',
                request_serializer=robot__pb2.CurrentAnglesRequest.SerializeToString,
                response_deserializer=robot__pb2.CurrentAnglesResponse.FromString,
                )


class RobotControllerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAngles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=robot__pb2.MotorAnglesRequest.FromString,
                    response_serializer=robot__pb2.MotorAnglesResponse.SerializeToString,
            ),
            'GetAngles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAngles,
                    request_deserializer=robot__pb2.CurrentAnglesRequest.FromString,
                    response_serializer=robot__pb2.CurrentAnglesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AiInvest.Robotics.GrpcServer.RobotControllerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotControllerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AiInvest.Robotics.GrpcServer.RobotControllerServer/Move',
            robot__pb2.MotorAnglesRequest.SerializeToString,
            robot__pb2.MotorAnglesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAngles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AiInvest.Robotics.GrpcServer.RobotControllerServer/GetAngles',
            robot__pb2.CurrentAnglesRequest.SerializeToString,
            robot__pb2.CurrentAnglesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
