# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x1c\x41iInvest.Robotics.GrpcServer\"$\n\x12MotorAnglesRequest\x12\x0e\n\x06\x61ngles\x18\x01 \x03(\x02\"\x15\n\x13MotorAnglesResponse\"&\n\x14\x43urrentAnglesRequest\x12\x0e\n\x06\x61ngles\x18\x01 \x01(\t\"\'\n\x15\x43urrentAnglesResponse\x12\x0e\n\x06\x61ngles\x18\x01 \x01(\t2\xfa\x01\n\x15RobotControllerServer\x12k\n\x04Move\x12\x30.AiInvest.Robotics.GrpcServer.MotorAnglesRequest\x1a\x31.AiInvest.Robotics.GrpcServer.MotorAnglesResponse\x12t\n\tGetAngles\x12\x32.AiInvest.Robotics.GrpcServer.CurrentAnglesRequest\x1a\x33.AiInvest.Robotics.GrpcServer.CurrentAnglesResponseB&\xaa\x02#AiInvest.Robotics.GrpcServer.Protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002#AiInvest.Robotics.GrpcServer.Protos'
  _MOTORANGLESREQUEST._serialized_start=45
  _MOTORANGLESREQUEST._serialized_end=81
  _MOTORANGLESRESPONSE._serialized_start=83
  _MOTORANGLESRESPONSE._serialized_end=104
  _CURRENTANGLESREQUEST._serialized_start=106
  _CURRENTANGLESREQUEST._serialized_end=144
  _CURRENTANGLESRESPONSE._serialized_start=146
  _CURRENTANGLESRESPONSE._serialized_end=185
  _ROBOTCONTROLLERSERVER._serialized_start=188
  _ROBOTCONTROLLERSERVER._serialized_end=438
# @@protoc_insertion_point(module_scope)
